"""removed name column

Revision ID: 1eca0edf9be1
Revises: 2c2f751a92b7
Create Date: 2025-08-08 14:29:44.855629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1eca0edf9be1'
down_revision: Union[str, Sequence[str], None] = '2c2f751a92b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=35),
               existing_nullable=True)
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', mysql.VARCHAR(length=50), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.String(length=35),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=True)
    # ### end Alembic commands ###
