"""switch uuid default function

Revision ID: 4fcdf4ec58ed
Revises: 1eca0edf9be1
Create Date: 2025-08-08 14:44:12.523684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fcdf4ec58ed'
down_revision: Union[str, Sequence[str], None] = '1eca0edf9be1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
